__tests__/index.test.js
__tests__/lib/style-formatting/index.test.js
package-lock.json
package.json
src/index.js

So what happens right now if you supply a query parameter that has characters that should be encoded, and that parameter does not have serialization configured, it'll be inserted into the HAR and generate an API request that is 100% not what you want.
For example, the following example from [api](https://npm.im/api):
```js
const spec = {
servers: [
{ url: 'https://httpbin.org' }
],
paths: {
'/anything': {
get: {
parameters: [
{ name: 'pound', in: 'query' },
{ name: 'hash', in: 'query' },
{ name: 'array', in: 'query' },
{ name: 'weird', in: 'query' },
],
},
},
},
};
const sdk = require('./packages/api')(spec);
(async () => {
await sdk.get('/anything', {
pound: 'something&nothing=true',
hash: 'hash#data',
array: 'where[4]=10',
weird: 'properties["$email"] == "testing"',
}).then(res => { …
```

fix: always ensure that query parameters are properly encoded

---

__tests__/__snapshots__/index.test.js.snap
__tests__/index.test.js
__tests__/lib/style-formatting/index.test.js
src/index.js
src/lib/style-formatting/index.js
src/lib/style-formatting/style-serializer.js

This refactors our handling of un-styled query parameters to always make sure that we encode, and don't double-encode, data where we support it.
Fix in support of RM-1986.
See tests.

fix: quirks with un-styled query parameters not always being encoded

---

__tests__/lib/style-formatting/index.test.js
src/lib/style-formatting/style-serializer.js

This fixes a quirk in the new query parameter encoding work (#16, #17) where if a query parameter had an unencoded percent sign in it, the library would crash when attempting to determine if it was already encoded.
This will resolve the problem @Dashron found in https://github.com/readmeio/api/pull/331#issuecomment-912757432.
See tests.

fix: bug where query parameters with percent signs would crash the library

---

__tests__/lib/style-formatting/index.test.js
src/lib/style-formatting/style-serializer.js

Add support for pipe delimited and space delimited objects, both of which are styles that were added for OAS 3.1
Check out the unit tests.

feat(styles): add space and pipe delimited support for objects per 3.1

---

__tests__/requestBody.test.js
package-lock.json
package.json

This resolves an issue with our `remove-undefined-objects` dependency where it was mistakenly filtering out null-assigned object properties from our payloads.
See https://github.com/readmeio/remove-undefined-objects/pull/8 for details.

fix: issue where null-assigned object properties would be filtered out

---

src/index.js
test/requestBody.test.js

We already have handling for this further up in the library but not at this particular line, and if we have a spec right now that has a `requestBody` but no `schema` we're throwing an error.

fix: add handling for when `requestBody` is present w/o a `schema`

---

package-lock.json
package.json
src/index.js
test/requestBody.test.js

| 🚥 Fix RM-3195 |
| :-- |
There's a bug in [valid-data-url](https://npm.im/valid-data-url) where it doesn't recognize data URLs that have underscores as being valid. They are!
I've submitted a fix upstream but in the meantime instead of waiting for that to be merged, published, and then merged into [parse-data-url](https://npm.im/parse-data-url), and published, I've soft forked both libraries and merged them into [@readme/data-urls](https://npm.im/@readme/data-urls).

fix: support for filenames that have underscores in them

---

src/lib/configure-security.ts
test/__datasets__/security-quirks.json
test/auth.test.ts
test/lib/configure-security.test.ts

| 🚥 Fix RM-5081 |
| :-- |
This fixes a problem in our `authorization` header construction where if an endpoint accepted either Basic or Bearer auth, and only specified data for the Basic auth portion, we'd add the `authorization` header twice: once with their data, and once with `undefined` as the value.
This would ultiumately bubble up into [@readme/oas-to-snippet](https://npm.im/@readme/oas-to-snippet) where we'd only show `authorization: undefined` in the code snippet:

fix: issue where auth header may be sent twice

---

.eslintrc
src/index.ts
test/parameters.test.ts

In order to allow `Accept` headers to be sent in api (https://github.com/readmeio/api/issues/448), I need to fix this issue where we're always returning the `Accept` header for a HAR as the first defined content type. Since we prefer JSON for everything else it makes sense to also prefer a JSON response.
I'm not considering this to be a breaking change.

fix: preferring JSON response content accept headers over everything else

---

src/index.ts
test/auth.test.ts
test/parameters.test.ts

Like I did in #130 for `Accept` headers, this allows us to manually specify an `Authorization` header in the form data, bypassing any auth data that's supplied to the library.
Fix in support of RM-4020.

feat: ability to manually specify an `authorization` header in formData

---

src/index.ts
test/__datasets__/multipart-form-data/oneOf-requestbody.json
test/requestBody.test.ts

| 🚥 Fixes CX-362 |
| :---------------- |
This fixes a quirk with certain `multipart/form-data` schema shapes where if it were set up as a nested `oneOf` or `anyOf` then the HAR that we would generate would dump everything into `postData.text` instead of `postData.params`. This would further cascade into `@readme/oas-to-snippet` where the snippet we'd generate for these situations would have no parameters because it's expecting those parameters to be in `postData.params`.

fix: quirk with multipart/form-data schema payloads being handled as `text`

---

.eslintrc
package-lock.json
package.json
src/index.ts
src/lib/utils.ts
test/requestBody.test.ts

| 🚥 Fixes CX-229 |
| :---------------- |
This fixes a quirk in our handling of schemas with `format: json` where we only supported them if they were at the top-most level in the schema. If you had an object with one of its properties being `format: json`, or an array of objects with the same, that JSON object would be stringified into the HAR we generate.

fix: support for deeply nested `format: json` schemas

---

src/index.ts
src/lib/utils.ts
test/__datasets__/deeply-nested-json-formats.json
test/requestBody.test.ts

The work I did in https://github.com/readmeio/oas-to-har/pull/218 had some issues with `format: json` schemas that were nested inside of a `oneOf`.

fix: handling for `format: json` schemas in polymorphic schemas

---

src/lib/style-formatting/index.ts
test/lib/style-formatting/index.test.ts

| 🚥 Resolves CX-124 |
| :---------------- |
Currently, if a customer uses `style: deepObject` but they don't explicitly add `explode: true`, our logic is defaulting `explode: false` which returns `undefined` since `deepObject && explode: false` isn't a thing according to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#style-examples). This causes anything the user types in the input to return `undefined`.
I added an extra check in our logic for `shouldExplode()` to ensure that anytime the style is set to `deepObject`, we'll automatically explode the parameter.
I'll put this into the PR for the main repo too but leaving the info here for visibility sake:
This is what the test looks like before my change:
The `color` object has a value of `undefined` …

fix: make `explode:true` default for deepObject styles

---

.github/workflows/ci.yml
.npmignore
package-lock.json
package.json
src/index.ts
src/lib/style-formatting/style-serializer.ts
src/lib/utils.ts
test/.eslintrc
test/auth.test.ts
test/index.test.ts
test/lib/configure-security.test.ts
test/lib/style-formatting/index.test.ts
test/lib/style-formatting/multipart-form-data.test.ts
test/parameters.test.ts
test/requestBody.test.ts

I am **obsessed** with [Vitest](https://vitest.dev/). Look at these gains! 💪
```
Test Suites: 7 passed, 7 total
Tests:       2 skipped, 2 todo, 271 passed, 275 total
Snapshots:   0 total
Time:        2.34 s
Ran all test suites.
npx jest  18.00s user 1.38s system 637% cpu 3.040 total
```
```
Test Files  7 passed (7)
Tests  271 passed | 2 skipped | 2 todo (275)
Start at  20:27:36
Duration  593ms (transform 838ms, setup 0ms, collect 1.91s, tests 348ms, environment 1ms, prepare 398ms)
npx vitest run  2.99s user 0.65s system 363% cpu 0.998 total
```

refactor(test): moving tests over to vitest

---

package.json
src/index.ts
src/lib/configure-security.ts
src/lib/types.ts
tsup.config.ts

I believe this is a quirk with `tsup` where default export functions don't play nicely with CJS repositories. This PR slightly shifts things around so all types are stored in a separate file, which is now surfaced in our `exports`.
Before:
After:
If tests pass and ATTW seems to like these changes, we should be good to go!

fix: split out type exports

---

.eslintrc
package-lock.json
package.json
src/index.ts
src/lib/utils.ts

Fixes an issue I saw when attempting to bump this package dep in https://github.com/readmeio/api/pull/735:
This project is ESM already so I think this should be a patch change. If tests pass then I think we should be good to go!

refactor: use `lodash-es` over `lodash`

---

src/lib/style-formatting/style-serializer.ts

😬 not sure how this got in here! This PR shuffles functions around a bit to address errors like this:
Do tests pass?

fix: don't use module

---

.eslintrc
package-lock.json
package.json
src/index.ts
src/lib/utils.ts

| 🚥 Resolves #244 |
| :------------------- |
Turns out, the fix in #243 was actually the problem and we didn't need #242 at all! So this restores our existing, very bad, `lodash` usage.
If tests pass we should be good to go! I actually tried `npm link`-ing this repo to the `api` repo and tried it with both CJS and ESM and the results were promising.

revert: bring back old-school lodash

---

src/index.ts
src/lib/utils.ts

| 🚥 (hopefully) resolves #244 |
| :------------------- |
Turns out #245 didn't work 😔 seeing this error now:
this whack-a-mole stuff is exhausting 😮‍💨
Unfortunately my `npm link` means of testing this has been yielding false-positives, so we won't really know until we publish this 🫠

fix: try loading `lodash` exports a different way

---

.eslintrc
package-lock.json
package.json
src/index.ts
src/lib/configure-security.ts
src/lib/style-formatting/index.ts
src/lib/style-formatting/style-serializer.ts
src/lib/utils.ts
test/auth.test.ts
test/index.test.ts
test/lib/configure-security.test.ts
test/lib/style-formatting/index.test.ts
test/lib/style-formatting/multipart-form-data.test.ts
test/parameters.test.ts
test/requestBody.test.ts

| 🚥 Resolves #244 |
| :------------------- |
I feel like every iteration of this is a new discovery into the kinds of errors this work yields:
I also brought in our latest ESM-flavored `eslint-config` made a few fixes according to that, as well as brought back type-checking and made a small fix there.
🫠

fix: another attempt to get lodash working
